Update vault-integration.yml

diff --git a/.github/workflows/vault-integration.yml b/.github/workflows/vault-integration.yml
--- a/.github/workflows/vault-integration.yml
+++ b/.github/workflows/vault-integration.yml
@@ -11,7 +11,7 @@ jobs:
 
     services:
       vault:
-        image: vault:1.13.3
+        image: vault:1.13.7
         ports:
           - 8200:8200
         options: >
@@ -36,7 +36,12 @@ jobs:
       - name: Verify Vault Container Logs
         run: |
           docker ps -a
-          docker logs $(docker ps -q --filter "ancestor=vault:1.13.3") || echo "Vault logs are unavailable"
+          docker logs $(docker ps -q --filter "ancestor=vault:1.15.0") || echo "Vault logs are unavailable"
+
+      - name: Check Container Status
+        run: |
+          docker ps -a
+          docker inspect $(docker ps -aq --filter "ancestor=vault:1.15.0") || echo "Container inspect failed"
 
       - name: Install Vault CLI
         run: |
